### ISSUE TITLE
Mutable tags are dangerous

### ISSUE THREAD

**Issue by joshgubler** [byu-oit/terraform-aws-ecr#2]
https://github.com/byu-oit/terraform-aws-ecr/blob/8a2fa2690c42aaf37a64808c7b79025094bc711c/variables.tf#L9

We've had production impact because we didn't recognize the implications of using mutable tags. (Code is built, but not deployed. Build moves the `prd` tag. Docker container crashes randomly and gets replaced by new code before we were ready.)

Any reason we can't make `immutable` be the default? Any reason we can't be even more strict and not allow mutable tags?

**Comment by yoshutch** [comment]
The only reason why I made MUTABLE default is that's the default AWS has already. I'm planning on our pattern module to default it to IMMUTABLE.

I'm fine if we want to bake some opinions into our defaults of the building block modules, so long as we allow for it to be overwritten.

**Comment by joshgubler** [comment]
Cool. Let's make IMMUTABLE the default.
